### PR TITLE
new image

### PR DESCRIPTION
**Pull request by Jay4869**
replace older p-value image

### CODE REVIEW

**Comment by Jay4869** [comment]
@amandazhang  also T-test image also can add into report

**Comment by amandazhang** [comment]
Okay, I'm looking into it.

**Comment by amandazhang** [comment]
@Jay4869 Your image is now in the code file, how can I move it into paper/image file?

**Comment by Jay4869** [comment]
@amandazhang  did you get it? If not, I do it!

**Comment by amandazhang** [comment]
No, save me:)

**Pull request merged**
