### PR TITLE
New convo

### PR DESCRIPTION
**Pull request by Jay4869**
I am working on re-scaling condition to make a high solution neural. So far, I am using `cond2.txt` which contains two block tests and binary trial with TR(2.5).

After I produced neural prediction, going to redo the convo-response and re-calculate the beta hat for linear regression. 

please check the idea, should be on the right track~
@lizeyuyuz @amandazhang

### CODE REVIEW

**Comment by amandazhang** [comment]
@Jay4869  Just want to make sure you did perform these on the new dataset that has been preprocessed right?

**Comment by Jay4869** [comment]
At this point, I completed to generated new neural convo

**Comment by Jay4869** [comment]
@amandazhang  @lizeyuyuz  As talking with matthew today, the new version dataset is only changing the grid so that make images plot nice, but there are still noise in dataset, so we still need to do if necessary for our analysis

**Comment by Jay4869** [comment]
Since I need to do convo function to produce convo response, I merge pull request by myself

**Pull request merged**
