### PR TITLE
add p-map and p-matrix

### PR DESCRIPTION
**Pull request by Jay4869**
improve basic-modeling.py to generate images `p-value-map` and `p-value-matrix`
Also, updating `read_image.py`

### CODE REVIEW

**Comment by amandazhang** [comment]
@Jay4869 Jay, can you add contour to the p-maps to make brain area more clear?

**Comment by Jay4869** [comment]
So far, I don't how to do it such as mark the sub-area in red. I need to ask someone is familiar with python ploting

**Comment by amandazhang** [comment]
@Jay4869 And also compared to p-map we've seen in the reference paper, do you also think the marked area should be smoother?

**Comment by Jay4869** [comment]
So far, I only make the sub-area be black, but If we can mark in color 'red', the problem should be solved. Do you want to take care of this part?

**Comment by amandazhang** [comment]
Okay, I'll take care of this part. More details tmr.

**Comment by Jay4869** [comment]
I would like to merge this branch to the master at this point, and Qingyuan will improve our p-value map beyond my `basic-modeling.py`

**Pull request merged**
